---
title: '产业升级、宏观政策与区域一体化的溢出效应'
subtitle: '——基于国际贸易网络的视角'
author: '黄蒙'
date: "`r Sys.Date()`"
output:
  bookdown::gitbook:
    config:
      download: pdf
      edit: null
      fontsettings:
        family: sans
        size: 2
        theme: sepia
      search: no
      toc:
        after: 'IWEP'
        before: 'GSCASS'
    includes:
      in_header: _header.html
  bookdown::word_document2:
    reference_docx: template.docx
  bookdown::pdf_book:
    citation_package: natbib
    includes:
      in_header: preamble.tex
    keep_tex: yes
    latex_engine: xelatex
    toc: yes
    toc_depth: 2
  bookdown::html_document2:
    code_folding: show
    df_print: paged
    fig_caption: yes
    highlight: haddock
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: no
csl: china-journal-of-economic-research.csl
biblio-style: apalike
delete_merged_file: yes
description: ''
documentclass: article
language:
  label:
    def: 定义
    exm: 例
    fig: 图
    proof: '证明: '
    solution: '解: '
    tab: 表
    thm: 定理
  ui:
    chapter_name: ''
link-citations: yes
bibliography: mybib.bib
site: bookdown::bookdown_site
abstract: ''
nocite: |
  @costinot2014
---

```{r setup, include=FALSE}
## global options
knitr::opts_chunk$set(
  fig.width = 6, fig.asp = 0.618,
  out.width = "80%", fig.align = "center",
  fig.path = 'Figures/', fig.show = "hold",
  warn = 1, warning = FALSE, message = FALSE, echo = TRUE, 
  comment = '', collapse = F, 
  cache = T, cache.comments = F, autodep = TRUE
  )

pdf.options(height = 10/2.54, width = 10/2.54) # 注意：此设置要放在最后
```


# 导言

## 研究背景

## 文献综述

## 创新之处

1. 设法将投入产出关系融入 EK 模型。

2. 观察各种冲击对贸易网络结构的影响。


## 全文结构

# 理论模型

　　加入多部门投入产出关系^[投入产出表中的数十个产业，各产业技术不同。但直观上，作为较大的国家，要素密集度相似的产业应该有相似的技术水平。] 的 EK 模型[@EK2002]。所有部门的生产都需要劳动力和其他部门的中间产品。投入系数通过投入产出表获得。

　　进一步的扩展考虑将劳动分为熟练劳动力和不熟练劳动力两种要素，毕竟当代世界，不如此无法说明很多现象。

## 偏好：D-S Lite 型

　　设各国代表性消费者的偏好相同，以 C-D 形式消费 $M$ 个部门的产品，形如：
$$
U \equiv \prod_{s=1}^M  \left\{\left[\int_0^1 \left( Q^s(\omega)\right)^{\frac{\sigma^s-1}{\sigma^s}}d\omega  \right]^{\frac{\sigma^s}{\sigma^s-1}}\right\}^{\alpha^s}, \text{  其中 }\sum_{s=1}^M \alpha^s=1
$$

　　则每个国家的最优化问题都是：
$$
\left\{
\begin{aligned}
&\max_{Q^s(\omega)} \prod_{s=1}^M  \left\{\left[\int_0^1 \left( Q^s(\omega)\right)^{\frac{\sigma^s-1}{\sigma^s}}d\omega  \right]^{\frac{\sigma^s}{\sigma^s-1}}\right\}^{\alpha^s} \\
&\text{s.t.} \sum_{s=1}^M \int_0^1 P^s(\omega)Q^s(\omega)d\omega=I
\end{aligned}
\right.
$$

　　均衡时可解得^[详见附录 A.1.1。] 
$$
Q^s(\omega)=\frac{\alpha^sI}{p^s}\left[\frac{p^s}{P^s(\omega)}  \right]^{\sigma^s}
$$

　　其中价格指数 
$$
p^s=\left[\int_0^1 \left(P^s(\omega)\right)^{1-\sigma^s}d\omega\right]^{\frac{1}{1-\sigma^s}}
$$

　　数量指数
$$
q^s=\left[\int_0^1 \left(Q^s(\omega)\right)^{\frac{\sigma^s-1}{\sigma^s}}d\omega\right]^{\frac{\sigma^s}{\sigma^s-1}}
$$

　　且有
$$
p^sq^s=\int_0^1 P^s(\omega)Q^s(\omega)d\omega=\alpha^sI
$$

## 生产函数：规模收益不变

　　设生产 $s$ 部门某种产品 $\omega$ 的生产函数为：
$$
y^s(\omega)\equiv\frac{z^s(\omega)}{(\beta^s)^{\beta^s}(1-\beta^s)^{1-\beta^s}}L^{\beta^s}\prod_{t=1}^M\left\{\left[\int_0^1 \left(Q^{t}(\omega)\right)^{\frac{\sigma^t-1}{\sigma^t}}d\omega\right]^{\frac{\sigma^t}{\sigma^t-1}}\right\}^{\beta^{st}}
$$

　　其中 $\sum_{t=1}^M \beta^{st}=1-\beta^s$

　　可以证明，$s$ 部门单位投入的成本为^[详见附录 A.1.2。] 
\begin{align}
c^s=w^{\beta^s}\prod_{t=1}^M(p^{t})^{\beta^{st}} (\#eq:1)
\end{align}

## 市场结构：完全竞争

　　在一国内部，企业获得零利润，产品价格等于平均成本。在国家之间，货物的跨境存在冰山型贸易成本，表示为：
$$
\left\{\begin{array}{c}{d_{i i}=1} \\ {d_{j i}>1, \forall j \neq i}\end{array}\right.
$$

　　则 $i$ 国 $s$ 部门的产品 $\omega$ 在 $j$ 国的价格为：
$$
P_{ji}^s(\omega)=P_{ii}^s(\omega)d_{ji}=\frac{c_i^s}{z_i^s(\omega)}d_{ji}
$$

　　$j$ 国在全世界范围内挑选最低价，$s$ 部门 $\omega$ 产品在 $j$ 国的最终价格为：
$$
\begin{aligned}
P_{j}(\omega)=\min \left\{P_{ji}^s(\omega) ; i=1, \cdots, N\right\}
\end{aligned}
$$

## 技术：Fréchet 分布

　　设 $i$ 国 $s$ 部门的技术参数 $z_i^s(\omega)$ 为一个随机变量 $Z_i^s$，服从 Fréchet 分布，即 $Z_i^s \sim F_i^s(z) \equiv \exp(-T_i^sz^{-\theta^s})$。可得价格的分布函数：
$$
P_{ji}^s(\omega) \sim G_{ji}^s(p)=1-\exp \left[-T_{i}^s ( {{c_i^s}d_{ji}})^{-\theta^s}p^{\theta^s}\right]
$$

　　和
$$
P_{j}^s(\omega)\sim G_j^s(p)=1-\exp\left\{-\left[\sum_{1}^{N}T_{i}^s ( {{c_i^s}d_{ni}})^{-\theta^s}\right]p^{\theta^s}\right\}
$$

　　其中，$G_j^s(p)$ 可以改写为
$$
\left\{
\begin{aligned}
G_j^s(p)&=1-\exp (-\Phi_j^sp^{\theta^s}) \\
\Phi_j^s&\equiv\sum_{1}^{N}T_{i}^s ( {{c_i^s}d_{ji}})^{-\theta^s}
\end{aligned}
\right.
$$

　　继而可证价格指数满足
\begin{align}
p_j^s&=\gamma^s(\Phi_j^s)^{-\frac{1}{\theta^s}} (\#eq:2) 
\end{align}

　　其中 $\gamma^s \equiv \left[\Gamma(\frac{\theta^s+1-\sigma^s}{\theta^s})\right]^\frac{1}{1-\sigma^s}=\text{constant}$


## 外生工资下的均衡

　　$j$ 国从 $i$ 国进口 $s$ 部门产品的支出占 $j$ 国 $s$ 部门产品总支出的比例 $\pi_{ji}^s$ 满足
$$
\pi_{ji}^s \equiv \frac{X_{j i}^s}{X_{j}^s}=\frac{T_{i}^s\left(c_{i}^s d_{j i}\right)^{-\theta^s}}{\Phi_{j}^s}
$$

　　将\@ref(eq:2)代入，得
\begin{align}
\pi_{ji}^s =T_{i}^s\left(\frac{\gamma^sd_{j i}c_{i}^s}{p_j^s} \right)^{-\theta^s}  (\#eq:3) 
\end{align}

　　因 $\sum_{i=1}^N \pi_{ji}^s=1$，代入\@ref(eq:3)可推出
$$
p_j^s=\gamma^s\left[\sum_{i=1}^N T_i^s\left(d_{j i}c_{i}^s\right)^{-\theta^s}\right]^{-1/\theta^s}
$$

　　将\@ref(eq:1)代入该式，得
\begin{align}
p_j^s=\gamma^s\left\{\sum_{i=1}^N T_i^s\left[d_{j i}w_i^{\beta_i^s}\prod_{t=1}^M(p_i^{t})^{\beta_i^{st}}\right]^{-\theta^s}\right\}^{-1/\theta^s} (\#eq:4) 
\end{align}

　　若 $N$ 个工资变量均为外生变量，则\@ref(eq:4)包含 $N\times M$ 个方程和相同数量的未知数，可以把各国的价格指数完全解出。但要使工资内生化，还需要额外 $N$ 个方程。

## 工资内生化：贸易平衡条件

　　给定各国规模 $L$，则有 $N$ 个贸易平衡方程：
\begin{align}
w_iL_i&=\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j \nonumber \\
&=\sum_{j=1}^N\left\{\sum_{s=1}^MT_{i}^s\left[\frac{\gamma^sd_{j i}w_i^{\beta_i^s}\prod_{t=1}^M(p_i^{t})^{\beta_i^{st}}}{p_j^s} \right]^{-\theta^s}\alpha_j^s\right\}w_jL_j (\#eq:5) 
\end{align}

　　\@ref(eq:5)与\@ref(eq:4)联立，理论上即可获得模型完整的解。

## 对数线性化

　　为了得到解析解，对方程组\@ref(eq:4)、\@ref(eq:5)进行对数线性化，求解外生冲击发生后，各变量相对于均衡值的变动比例。为此，令 $\hat x \equiv dx/x$，表示变量 $x$ 对外生冲击的反应。

　　原方程组经过对数线性化后成为以下方程组^[详见附录 A.1.3。] ：
\begin{align}
&\sum_{i=1}^N \sum_{t=1}^M \pi_{ji}^s\beta_i^{st} \hat p_i^t-\hat p_j^s+\sum_{i=1}^N \pi_{ji}^s\beta_i^s\hat w_i=\frac{1}{\theta^s}\sum_{i=1}^N\pi_{ji}^s\hat T_i^s-\sum_{i=1}^N\pi_{ji}^s\hat d_{ji} (\#eq:6) \\
&\theta^s\sum_{t=1}^M\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\beta_i^{st} \hat p_i^t-\theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat p_j^s \nonumber \\
& +(w_iL_i+\theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\beta_i^s)\hat w_i-\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat w_j \nonumber \\
&= w_iL_i\hat T_i^s - \theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat d_{ji}-w_iL_i\hat L_i+\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat L_{j} (\#eq:7) 
\end{align}


## 求解线性方程组

　　于是，我们可以将对数线性化的方程组\@ref(eq:6)、\@ref(eq:7)写为 $AX=B$ 的形式，并求得 $X=A^{-1}B$。其中：

1. $X$ 为 $(M\times N+N)$ 维向量：
$$
X \equiv (\hat p_1^1,\hat p_1^2, \cdots, \hat p_1^M, \hat p_2^1, \cdots, \hat p_2^M, \cdots,\hat p_N^1,\cdots, \hat p_N^M, \hat w_1, \hat w_2,\cdots, \hat w_N)^\prime
$$

2. $B$ 也是 $(M\times N+N)$ 维向量：
$$
B \equiv \left(\hat b_1^1,\hat b_1^2, \cdots, \hat b_1^M, \hat b_2^1, \cdots, \hat b_2^M, \cdots,\hat b_N^1,\cdots, \hat b_N^M, \hat b_1, \hat b_2,\cdots, \hat b_N \right)^\prime
$$

其中 
$$
\left\{
\begin{aligned}
\hat b_j^s & \equiv \frac{1}{\theta^s}\sum_{i=1}^N\pi_{ji}^s\hat T_i^s-\sum_{i=1}^N\pi_{ji}^s\hat d_{ji} \\ 
\hat b_i & \equiv w_iL_i\hat T_i^s - \theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat d_{ji}-w_iL_i\hat L_i+\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat L_{j}
\end{aligned}
\right.
$$

3. 系数矩阵 $A$ 为 $(M\times N+N)$ 阶方阵^[详见附录 A.1.4。] 

<div><font size = 2>

$$
\begin{array}{l}
A = \\
\left(\begin{matrix}
t_{1111}-1 & \cdots & t_{111M}  & \cdots & t_{11N1} &\cdots&t_{11NM}&t_{111}&\cdots&t_{11N} \\
t_{1211} & \cdots & t_{121M}  & \cdots & t_{12N1} &\cdots&t_{12NM}&t_{121}&\cdots&t_{12N} \\
\vdots & \vdots & \vdots & \vdots & \vdots &\vdots&\vdots&\vdots&\vdots&\vdots \\
t_{NM11} & \cdots & t_{NM1M}  & \cdots & t_{NMN1} &\cdots&t_{NMNM}-1&t_{NM1}&\cdots&t_{NMN} \\
l_{11}-m_{111} & \cdots & l_{1M}-m_{11M} & \cdots & -m_{1N1} &\cdots&-m_{1NM}& l_1-m{11}&\cdots&-m_{1N}\\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots\\
-m_{N11} & \cdots & -m_{N1M}  & \cdots & l_{N1}-m_{NN1} & \cdots & l_{NM}-m_{NNM} & -m_{N1} &\cdots & l_N-m_{NN} \\
\end{matrix}\right)
\end{array}
$$

</font></div>

其中
$$
\left\{
\begin{aligned}
t_{jsit} &= \pi_{ji}^s\beta_i^{st} \\
t_{jsi}&=\pi_{ji}^s\beta_i^s \\
l_{it} & = \theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\beta_i^{st} \\ 
l_i & = w_iL_i+\theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\beta_i^s \\
m_{ijs} & = \theta^s\sum_{j=1}^N\sum_{s=1}^M \pi_{ji}^s\alpha_j^sw_jL_j\\ 
m_{ij} & = \sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j
\end{aligned}
\right.
$$

　　由 $X=A^{-1}B$，便可以研究三种外生冲击对内生变量的影响。这三种外生冲击分别是技术 $\hat T_i^s$、贸易成本 $\hat d_{ji}$ 和国家规模 $\hat L_i$。当然，根据具体需要，也可以将 $\alpha$、$\beta$ 作为外生变量，研究偏好和投入产出关系变化对内生变量的影响。

# 参数估计和反事实模拟

## 参数估计

## 反事实模拟：产业缺失对福利的影响

　　通过实证研究论证德国、日本 $T^s$ 高的部门明显偏少。如果德国技术水平较高的部门像法国一样齐全，会发生什么。

　　日本相对于法德。

# 国际贸易网络

## 国际贸易网络演变的特征事实

## 理论推导

　　影响国际贸易网络结构的三要素：技术 $T^s$、规模 $\bar L$、地理 $d_{ij}$

## 贸易网络的国际政治经济学

社会网络分析（SNA）方法

# 产业升级（技术）的溢出效应

　　产业升级的本质是一个部门的技术进步，$T_i^B \uparrow$；产业革命中抢占新产业是在新产业中本国的 $T_i^B$ 一枝独秀得大



## 福利

## 贸易网络

## 小结

- 新一轮科技革命和产业革命方兴未艾  
- 新兴国家实现“弯道超车”的绝佳机会  
- 抢占新兴产业具有**最**重大的经济意义和国际政治意义  

# 宏观政策（规模）的溢出效应

　　在全球有效需求不足的大背景下，刺激性宏观政策可以大致视为劳动力增加

　　进一步的研究可以考虑货币政策和财政政策的区别

## 福利

德国保守的经济政策造成欧洲国家增长率的分化。美中刺激经济，拉动德国出口。德国出口扩张的程度，大于消费扩张的程度。因此，产业链处于德国上游的国家（向德国出口中间产品）被拉动，经济增长率比较高；而主要向德国出口最终消费品的国家，受到的拉动作用比较弱，经济增长率就比较低。——在欧盟内部，这有政治影响。

## 对产业的刺激

欧盟近年启动了欧洲防务基金项目，该项目资金雄厚，有望在数年后达到相当大的规模。该项目鼓励并资助欧盟国家展开军备研发上的合作，对当前普遍缺乏军费的欧洲国家具有相当大的吸引力。<http://kns.cnki.net//KXReader/Detail?TIMESTAMP=637089024206192500&DBCODE=CCND&TABLEName=CCNDPREP&FileName=JFJB201911070113&RESULT=1&SIGN=rV4DA34x5hk0IYrp%2btItZKBKz44%3d>

## 贸易网络


# 区域一体化（地理）的溢出效应

## 福利

## 贸易网络


# 结论


`r if (knitr::is_html_output()) '# 参考文献 {-}'`


# 附录 {-}

## A.1 模型推导 {-}

### A.1.1 偏好 {-}

　　进行两阶段最优化。

1. 第一阶段最优化

　　令数量指数 $q^s\equiv\left[\int_0^1 \left(Q^s(\omega)\right)^{\frac{\sigma^s-1}{\sigma^s}}d\omega\right]^{\frac{\sigma^s}{\sigma^s-1}}$，价格指数 $p^s\equiv\int_0^1 P^s(\omega)Q^s(\omega)d\omega/q^s$，则第一阶段最优化问题为：
$$
\left\{
\begin{aligned}
&\max_{q^s} \prod_{s=1}^M  (q^s)^{\alpha^s} \\
&\text{s.t.} \sum_{s=1}^M p^sq^s=I
\end{aligned}
\right.
$$

　　显然，这是一个 C-D 型偏好最优化问题。于是有 $p^sq^s=\alpha^sI$

2. 第二阶段最优化
$$
\left\{
\begin{aligned}
&\max_{Q^s(\omega)} \left[\int_0^1 \left(Q^s(\omega)\right)^{\frac{\sigma^s-1}{\sigma^s}}d\omega\right]^{\frac{\sigma^s}{\sigma^s-1}} \\
&\text{s.t.} \int_0^1 P^s(\omega)Q^s(\omega)d\omega=\alpha^sI
\end{aligned}
\right.
$$

　　由此解得
$$
\left\{
\begin{aligned}
& p^s=\left[\int_0^1 \left(P^s(\omega)\right)^{1-\sigma^s}d\omega\right]^{\frac{1}{1-\sigma^s}} \\
&Q^s(\omega)=\frac{\alpha^sI}{p^s}\left[\frac{p^s}{P^s(\omega)}  \right]^{\sigma^s}
\end{aligned}
\right.
$$

### A.1.2 生产 {-}

　　生产 $s$ 部门某种产品 $\omega$ 的成本最小化问题为
$$
\left\{
\begin{aligned}
&\min_{L, Q^{t}(\omega)} wL + \sum_{t=1}^M \int_0^1 P^t(\omega)Q^{t}(\omega)d\omega \\ 
&\text { s.t. } \frac{z^s(\omega)}{(\beta^s)^{\beta^s}\prod_{t=1}^M(\beta^{st})^{\beta^{st}}}L^{\beta^s}\prod_{t=1}^M\left\{\left[\int_0^1 \left(Q^{t}(\omega)\right)^{\frac{\sigma^t-1}{\sigma^t}}d\omega\right]^{\frac{\sigma^t}{\sigma^t-1}}\right\}^{\beta^{st}}
\end{aligned}
\right.
$$

　　为便于求解，将其对偶化为产量最大化问题，并进行三个换元

- 令效率指数 $k^s(\omega)\equiv\frac{z^s(\omega)}{(\beta^s)^{\beta^s}\prod_{t=1}^M(\beta^{st})^{\beta^{st}}}$，与 $L, K^{t}$ 无关
- 令 $t$ 部门中间品的数量指数 $K^{t}\equiv\left[\int_0^1 \left(Q^{t}(\omega)\right)^{\frac{\sigma^t-1}{\sigma^t}}d\omega\right]^{\frac{\sigma^t}{\sigma^t-1}}$
- 令 $t$ 部门中间品的价格指数 $p^t\equiv\left[\int_{0}^{1} \left(P^t(\omega)\right)^{1-\sigma^t} d\omega\right]^{\frac{1}{1-\sigma^t}}$，且有 $p^tK^{t}=\int_0^1 P^t(\omega)Q^{t}(\omega)d\omega$

　　于是最优化问题变为
$$
\left\{\begin{aligned}
\max_{L, K^{t}} k^s(\omega)L^{\beta^s}\prod_{t=1}^M(K^{t})^{\beta^{st}} \\
{\text { s.t. } wL + \sum_{t=1}^M p^tK^{t} = C}
\end{aligned}\right.
$$

　　易知均衡时有 $L=\beta^s C/w, K^t=\beta^{st}C/p^t$，因此生产 $s$ 部门 $\omega$ 产品的单价为 
$$\frac{C}{y^s(\omega)}=\frac{w^{\beta^s}\prod_{t=1}^M(p^{t})^{\beta^{st}}}{z^s(\omega)}$$

　　单价与效率 $z^s(\omega)$ 成反比，与单位投入的成本成正比，故 $s$ 部门单位投入的成本为
$$
c^s=w^{\beta^s}\prod_{t=1}^M(p^{t})^{\beta^{st}}
$$

### A.1.3 对数线性化 {-}

　　原方程组中包含两类方程，\@ref(eq:4)代表的一类为 $\sum_{i=1}^N \pi_{ji}^s=1$，\@ref(eq:5)代表的一类为 $w_iL_i=\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j$。

　　第一类方程可以化为 
$$\sum_{i=1}^N \pi_{ji}^s\hat \pi_{ji}^s=0$$

　　而 
$$\hat \pi_{ji}^s=\hat T_i^s + \theta^s\left[\hat p_j^s - \hat d_{ji}-\beta_i^s\hat w_i - \sum_{t=1}^M \beta_i^{st} \hat p_i^t\right]$$

　　代入上式得
$$
\sum_{i=1}^N \sum_{t=1}^M \pi_{ji}^s\beta_i^{st} \hat p_i^t-\hat p_j^s+\sum_{i=1}^N \pi_{ji}^s\beta_i^s\hat w_i=\frac{1}{\theta^s}\sum_{i=1}^N\pi_{ji}^s\hat T_i^s-\sum_{i=1}^N\pi_{ji}^s\hat d_{ji}
$$

　　第二类方程可以化为 
$$
\sum_{j=1}^N\sum_{s=1}^M\frac{\pi_{ji}^s\alpha_j^sw_jL_j}{w_iL_i}(\hat \pi_{ji}^s+\hat w_j +\hat L_j)=\hat w_i +\hat L_i
$$

将 $\hat \pi_{ji}^s$ 的表达式代入得
$$
\begin{aligned}
&\theta^s\sum_{t=1}^M\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\beta_i^{st} \hat p_i^t-\theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat p_j^s  \\
& +(w_iL_i+\theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\beta_i^s)\hat w_i-\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat w_j \\
&= w_iL_i\hat T_i^s - \theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat d_{ji}-w_iL_i\hat L_i+\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\hat L_{j}
\end{aligned}
$$

### A.1.4 矩阵分解 {-}

　　为了便于表示，对 $A$ 进行拆分

$$
A\equiv T+L+M
$$

　　其中，矩阵 $T$ 代表前 $(M \times N)$ 个方程的系数，$L$ 和 $M$ 代表最后 $N$ 个方程的系数。

1. $T$
$$
\begin{aligned}
T = & \left(\begin{matrix}
t_{1111} & t_{1112} & \cdots & t_{11NM} & t_{111} & \cdots & t_{11N} \\
t_{1211} & t_{1212} & \cdots & t_{12NM} & t_{121} & \cdots & t_{12N}\\
\vdots & \vdots & \ddots & \vdots & \vdots & \cdots & \vdots \\
t_{NM11} & t_{NM12} & \cdots & t_{NMNM} & t_{NM1} & \cdots & t_{NMN} \\
0 & 0 & \cdots & 0 & 0 & \cdots & 0 \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
0 & 0 & \cdots & 0 & 0 & \cdots & 0 \\
\end{matrix}\right)\\
+&\left(\begin{matrix}
-1 &0 & \cdots & 0 & 0 & \cdots & 0 \\
0 & -1 & \cdots & 0 & 0 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots & \vdots & \cdots & \vdots \\
0 & 0 & \cdots & -1 & 0 & \cdots & 0 \\
0 & 0 & \cdots & 0 & 0 & \cdots & 0 \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
0 & 0 & \cdots & 0 & 0 & \cdots & 0 \\
\end{matrix}\right)
\end{aligned}
$$

　　其中^[编程时可以用四重循环填充这个矩阵。] 
$$
\begin{aligned}
t_{jsit} &= \pi_{ji}^s\beta_i^{st} \\
t_{jsi}&=\pi_{ji}^s\beta_i^s 
\end{aligned}
$$

　　也就是说，$A_1$ 的前 $M \times N$ 行为 
$$
(\pi_{j1}^s\beta_1^{s1}, \cdots, \pi_{j1}^s\beta_1^{sM}, \cdots, \pi_{jj}^s\beta_j^{ss}-1  , \cdots,\pi_{jN}^s\beta_N^{s1},\cdots, \pi_{jN}^s\beta_N^{sM}, \pi_{j1}^s\beta_1^s, \cdots, \pi_{jN}^s\beta_N^s)
$$

　　一行内依次遍历 $t$ 和 $i$，行间依次遍历 $s$ 和 $j$；当 $(j,s)=(i,t)$ 时，矩阵元素要减一。最后 $N$ 行为零行。


2. $L$
$$
L = 
\left(\begin{matrix}
0 & \cdots & 0  & \cdots & 0 &\cdots&0&0&\cdots&0 \\
\vdots & \vdots & \vdots & \vdots & \vdots &\vdots&\vdots&\vdots&\vdots&\vdots \\
0 & \cdots & 0  & \cdots & 0 &\cdots&0&0&\cdots&0 \\
l_{11} & \cdots & l_{1M} & \cdots & 0 &\cdots&0& l_1&\cdots&0\\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \ddots & \vdots\\
0 & \cdots & 0  & \cdots & l_{N1} & \cdots & l_{NM} & 0 &\cdots & l_N \\
\end{matrix}\right)
$$

　　其中 
$$
\begin{aligned}
l_{it} & = \theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\beta_i^{st} \\ 
l_i & = w_iL_i+\theta^s\sum_{j=1}^N\sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j\beta_i^s
\end{aligned}
$$


3. $M$
$$
M = - 
\left(\begin{matrix}
0 & 0 & \cdots & 0 & 0 & \cdots & 0 \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
0 & 0 & \cdots & 0 & 0 & \cdots & 0 \\
m_{111} & m_{112} & \cdots & m_{1NM} & m_{11} & \cdots & m_{1N} \\
m_{211} & m_{212} & \cdots & m_{2NM} &  m_{21} & \cdots & m_{2N}\\
\vdots & \vdots & \ddots & \vdots & \vdots & \cdots & \vdots \\
m_{N11} & m_{N12} & \cdots & m_{NNM} & m_{N1} & \cdots & m_{NN} \\
\end{matrix}\right) 
$$

　　其中
$$
\begin{aligned}
m_{ijs} & = \theta^s\sum_{j=1}^N\sum_{s=1}^M \pi_{ji}^s\alpha_j^sw_jL_j\\ 
m_{ij} & = \sum_{s=1}^M\pi_{ji}^s\alpha_j^sw_jL_j
\end{aligned}
$$

　　将 $T, L, M$ 三部分加总，即可得 $A$.

## A.2 数据和代码 {-}
