# (PART) Word 篇 {-}

# Word 基础 {#chapter-word-basic}

## 快捷键 {#word-shortcut}

Table: (\#tab:word-short) word中的常用快捷键

**快捷键**|**功能**
----------|---------
Ctrl + D|字体
Ctrl + F|查找
Ctrl + G|定位
Ctrl + H|替换
Ctrl + K|插入超链接
Ctrl + N|新建
Ctrl + O|打开文件
Ctrl + P|打印
Ctrl + W|只关闭文件不关闭 Word 程序^[Word 程序打开很耗时，如果只是要关闭一个文件，仍要继续使用 Word 处理其他文件，最好用这个快捷键。] 
Alt + =|插入公式
F4|重复操作^[在excel中尤其好用！]
Tab|变为下一级标题（降级）
Shift + Tab|变为上一级标题（升级）
Shift + F5|将光标移到上次编辑的位置
Ctrl + Shift + F9|将域转变为纯文本
**选择文本**|
鼠标双击^[或：光标在词头，按Ctrl + Shift + Right；光标在词尾，按Ctrl + Shift + Left。]|选择一个单词
在段落的左侧空白处双击鼠标|选中一个段落
三击鼠标|选中一个段落
Ctrl + 单击|选中一个句子
Home/End|光标移动到行头/行尾
Ctrl + Home/End|光标移动到全文头/全文尾
Shift + Home/End|选中从光标到行头/行尾
Ctrl + Shift + Home/End|选中从光标到全文头/全文尾
Alt + 拖曳|垂直选中一块文本^[很多行文字有相同的前缀、后缀和中间部分，当你想编辑的时候，可以垂直选中、统一修改。]
F8|开启选择模式，以光标为选择的基点^[按1次F8开启选择模式，再按1次选中当前单词，2次选中句子，3次选中段落，4次选中全文。]；ESC取消
**复制粘贴**|
Ctrl + Shift + C/V|复制粘贴格式


## 一些技巧 {#word-skills}

1. 多样化粘贴，可以粘贴为链接，保持与数据源的更新能力
2. 删除不连续的空行：将两个回车\^p替换为一个回车\^p

# Word 界面 {#chapter-word-interface}

## “文件”选项卡

- 选项-校对-自动更正选项，该功能可以自动更正字词输入中的错误，也可以以自定义方式设定输入替换，如输入(a)自动替换为@，输入

## “开始”选项卡

- 字体-更改大小写  
- Ctrl + H  
  - 编辑-查找-高级查找，灵活运用通配符，“*”代表零个或多个任意字符，“?”代表一个任意字符  
  - 编辑-查找-高级查找，搜索选项里有“查找单词的所有形式(英文)”，例如可以通过动词原形查找到动词的其他形式
  - 编辑-查找-转到-定位，可以输入页号迅速前往某一页  

## “插入”选项卡
- 插图-屏幕截图-屏幕剪辑，可以很方便地截屏
- 插入日期时间可以勾选“自动更新”，便能够随系统日期自动更新
- 文本-首字下沉
- 文本-对象，若以这种方式插入图片，显示的只是一个图标，显示这里有一个图片对象，而非显示图片本身
- 文本-文档部件，文档部件库就是对某一段指定文档内容的封装手段，也就是对这段文档内容的保存和重复利用。因此，一些经常使用的表格、图片、自定义公式、公文版头、签名、段落等元素，都可以保存到文档部件库中。
- 链接-书签，用于记忆定位

## “设计”选项卡

- 页面背景-水印，配合文档加密。
- 文档格式-颜色-自定义颜色-“新建主题颜色”对话框，例如可以修改已访问的链接的颜色

## “审阅”选项卡

- 保护-限制编辑，可以选定部分内容，只有这些内容可以编辑，其他内容都不能编辑，以此保护固定不变的内容，防止误编辑和误删除

## “视图”选项卡
- 使用自动多级列表时，要删除原有的手动编号，最快捷的方法是在`大纲`视图中删除

# 样式

- 开始-编辑-选择-选定所有格式类似的文本^[强大的功能！特别时候修理未经样式整顿的文档。]
- 开始-样式功能组右下角-样式窗格最下面一行第三个按钮-管理样式对话框-导入/导出-管理器对话框，可以将某个文件已经调好的样式应用到其他文件
- 保存与应用样式集^[相比模板功能，只保存了样式，没有保存内容] ：设计-文档格式功能组中样式的下拉框。

# 表格

- 表格中加入斜线：表格工具|设计-边框-边框-斜下框线
- Ctrl + Shift + Enter 可以将表格纵向拆分为两个表格
- 表格工具-布局-重复标题行，可以使标题行出现在跨页表格的每页顶端
- 选中五段文字，复制，再选择表格的五行，粘贴，就可以一格一段了
- 表题注段落定义“开始-段落-换行与分页-与下段同页”，可以保持题注与表格始终处于同一页，避免表格的题注孤零零位于一页末尾的情况
- 表格工具-设计-表格样式，可以自定义表格样式，而后应用于所有表格

# 图片

- `图片工具|格式`-`排列`，从`嵌入`变成`环绕`，将图片`下移一层`，点击`选择窗格`才能同时出现图片和其上覆盖的文本框，在选择窗格中同时选中它们，`组合`，可以使其成为一个捆绑在一起的整体，再变回`嵌入`

# 页面设置

- 开始-段落-换行与分页：(1)孤行控制，避免页面顶部仅显示段落的最后一行和底部的仅显示段落的第一行；(2)与下段同页，保证前后两个段落始终在同一页中，特别适合表标题、表、图、图标题、图注释等段落样式。
- 布局-页面设置对话框-页边距-页码范围，选择“对称页边距”，就像书籍杂志一样，打印出来是左右对称的
- 布局-稿纸设置，可以使文字填写在稿纸中
- 设计-页面背景-页面颜色-填充效果，可以插入图片作为页面背景

# 域

- 插入-文档部件-域

类别中选择“链接和引用”，域名选择 StyleRef，就可以链接到某级标题了

\cleardoublepage 
