# (PART) Excel 篇 {.unnumbered}

# Excel 基础 {#chapter-Excel-basic}

## 快捷键

| 快捷键                                      | 功能                                                              |
|---------------------------------------------|-------------------------------------------------------------------|
| **编辑单元格**                              |                                                                   |
| F2/ESC                                      | 进入/退出单元格编辑状态                                           |
| Ctrl + $\rightarrow$ / $\leftarrow$         | 光标移动一个单词                                                  |
| Shift + $\rightarrow$ / $\leftarrow$        | 光标移动一个字符                                                  |
| Ctrl + Shift + $\rightarrow$ / $\leftarrow$ | 光标移动并选中一个单词                                            |
| Shift + Home / End                          | 光标移动到单元格的首/尾                                           |
| Ctrl + Delete                               | 删除当前行光标至行末的所有内容                                    |
| Alt + Enter                                 | 单元格内换行                                                      |
| **选择有数据的区域**                        |                                                                   |
| 选中有数据的单元格然后 Ctrl + A             | 选择当前连续的数据区域                                            |
| Ctrl + Shift + 箭头                         | 将单元格的选定范围扩展至活动单元格所在行列的下一个非空单元格      |
| Ctrl + Shift + Home/End                     | 将单元格的选定范围扩展至活动单元格所在行列的最初/后一个非空单元格 |

## 输入和编辑数据

-   在多个单元格中输入统一数据

    1.  选中所有单元格
    2.  输入数据
    3.  按 Ctrl + Enter

-   输入西文撇号`'`加数字即可获得文本类型的数值，如18位身份证号`'110100199911110202`

-   自动填充数据

    -   可以通过序列方式定义填充类型、步长和终止值
    -   可以填充自定义序列。文件-选项-高级-常规-编辑自定义列表-自定义序列对话框，添加[^part2-excel-1] 或导入[^part2-excel-2] 新序列
    -   按住右键拖动填充柄，可以选择如何填充，等比还是等差，按月还是按年，etc

-   控制数据的有效性。数据-数据工具-数据验证，教材P179

-   选择性粘贴功能极其强大，可以加减乘除，可以粘贴各种元素

-   移动行列：鼠标移到行列边缘变形后，按下 Shift 拖动

[^part2-excel-1]: 每输入一项按 Enter 换行输入下一项。

[^part2-excel-2]: 从一系列单元格。

## 修饰美化

### 自定义数字格式

建议先从已有的分类中点击一种，再点击"自定义"并在这个基础上修改。P187

### "表格"概念

指工作表中的部分区域，堪称表中表，点击后出现表格工具\|设计选项卡。

-   两种创建方法：

    1.  插入-表格功能组-表格
    2.  开始-样式功能组-套用表格格式

-   将表格转换为普通区域：表格工具\|设计-工具-转换为区域

### 条件格式

开始-样式组-条件格式

## 打印

页面布局-页面设置组

## 对数据的保护

-   在审阅-更改-保护工作表中限制对数据的改动

    -   有些单元格仍然是允许改动的，比如原始数据的输入，此时选定这部分允许改动的单元格，设置单元格格式对话框-保护选项卡-取消勾选锁定复选框，这部分单元格就会被排除在保护范围之外
    -   对于那些通过公式计算出来的单元格，不仅需要锁定，还需要隐藏公式，在设置单元格格式对话框-保护选项卡-勾选隐藏复选框，则公式不但不能被修改，还不能被看到
    -   若有一个区域，**数据和公式都希望隐藏**，而其他单元格不受影响[^part2-excel-3] 。则首先需要在设置单元格格式对话框-数字选项卡中将这个区域的分类设定为自定义格式、类型输入`;;;`，然后保护选项卡-勾选隐藏复选框，再审阅-更改-保护工作表

[^part2-excel-3]: 哪怕是同一行列的其他单元格

## 同时对多张工作表进行操作

-   选中多张工作表，形成工作表组后，可以批量操作
-   填充成组工作表：选中一块区域，选择其他工作表形成工作表组，开始-编辑-填充-至同组工作表

## 多窗口控制

1.  视图-窗口-新建窗口\
2.  视图-窗口-并排查看

# Excel 公式和函数

## 定义与引用名称

-   定义名称

    1.  在名称框中为一些常用单元格或区域定义名称，方便导航或绝对引用。
    2.  公式-定义的名称-定义名称/根据所选内容创建

## 日期和时间函数

日期和时间格式的数据，不论外观是什么，都是以数字形式储存的，如2013年1月20日是41294。必须使用专门处理日期的函数来处理，而其他如字符串函数取到的都是"41294"的一部分。

-   日期之间可以直接比较大小
-   日期单元格格式设定，周几为aaa，星期几为aaaa
-   weekday(,2) 返回1-7对应周一到周日

## 显示公式所引用的单元格之间的关系

-   公式-公式审核-追踪引用单元格/追踪从属单元格

## 使用公式的常见错误

P240

# Excel 图表

## 迷你图

折线；柱形；盈亏

## 图表的移动

图表工具\|设计-位置-移动图表

# 数据处理和分析

-   数据-数据工具-合并计算，对应 R 中 `rbind() %>% group_by() %>% summarize()`
-   数据-排序和筛选-排序，添加条件：主要关键字-次要关键字
-   数据-排序和筛选-高级，可以根据事先写好的条件区域进行复杂条件的高级筛选
-   数据-分级显示，分类汇总与分级显示
-   插入-表格-数据透视表，数据透视表是一种交互式表格

\cleardoublepage
