# (PART) PowerPoint 篇 {-}

# PowerPoint 基础 {#chapter-PowerPoint-basic}

## 快捷键

快捷键|功能
--|--
大纲视图下按 Enter|同一级别新的段落；若为标题级别，则新插入一张幻灯片
大纲视图下按 Ctrl + Enter|低一级别新的段落

## 从 Word 创建幻灯片

要求 Word 为大纲视图，只显示3级，然后关闭 Word ，在 PPT 中点击：开始-幻灯片-新建幻灯片-幻灯片（从大纲）

## 由幻灯片创建讲义

文件-导出-创建讲义-创建讲义

## 分节管理

右键新增节


# 编辑和美化

## 主题和背景
- 设计-主题，在下拉菜单中选择“浏览主题”，就可以选择另一个ppt文件，应用其主题
- 设计-背景格式


## 幻灯片母版

- 创建：视图-母版视图-幻灯片母版，幻灯片母版选项卡-编辑母版-插入幻灯片母版/删除
- 应用：开始-幻灯片-版式

## 幻灯片页码

- 插入：插入-文本-幻灯片编号
- 设置起始编号：设计-自定义-幻灯片大小-幻灯片编号起始值

## 删除备注

文件-信息-检查问题-检查文档-演示文稿备注，检查完毕后将备注全部删除

## 批量插入图片

插入-图像-相册-新建相册，选中要插入的多张图片，可以一次性插入PPT中，每张幻灯片里一张图片

## 多个对象相互遮挡

开始-编辑-选择-选择窗格，可以轻松选择被遮挡的对象（Word 中同理）

## SmartArt

- 快速创建：在一张已经定义文本层级的幻灯片上，右键单击后选择：转换为 SmartArt
- 大纲操作：欲添加一个同级图形块，不能直接在图上选中一块回车，这只会使图内文字换行；而应该在 SmartArt 的文本窗格（类似大纲视图）中将光标置于首行之前并回车


## 动作按钮

插入-形状的最后一行，有各种动作按钮

# 放映

## 动画

为 SmartArt 图形设置统一的动画后，可以**点击：动画-效果选项-系列-逐个，使 SmartArt 图形的每个形状逐个播放**。


## “切换”选项卡

幻灯片切换的出现方式和时间

## 放映幻灯片

- 幻灯片放映-开始放映幻灯片-自定义幻灯片放映，可以自定义n种放映方案，以适应不同场合
- 可以另存为.ppsx格式，ppsx只能在幻灯片放映视图（而不是普通视图）中打开，并**可以在没有安装 PowerPoint 的计算机上播放**



\cleardoublepage
 
